### ISSUE TITLE
Problem with "tslint --project . --fix"

### ISSUE THREAD

**Issue by xjuanc** [NG-ZORRO/nz-tslint-rules#1]
Hello everyone, I was trying to update our production project which holds 500+ modules and we certainly need this tool to make it work because manually doing so would be a nightmare. I've been the whole afternoon trying to make it work even copying and pasting your import example and haven't manage to do so.

Our imports are like following in the whole project:
![image](https://user-images.githubusercontent.com/11546865/94727444-070cfc00-035f-11eb-9fcc-7e27e14aec3b.png)

I'm using the following config:

![image](https://user-images.githubusercontent.com/11546865/94728476-92d35800-0360-11eb-8922-71f9c3c4d6c0.png)

package.json:

"ng-zorro-antd": "^9.3.0",
"typescript": "~3.8.3",
"nz-tslint-rules": "^0.901.2",
"@angular/core": "~9.1.12",

I'm executing the following command from the app root: 
"tslint --project ."

I've managed to be sure about the script execution with a console log in the nzSecondaryEntryImportsRule.js file

![image](https://user-images.githubusercontent.com/11546865/94729186-9f0be500-0361-11eb-983a-acef560d7f13.png)

Also I've notice that:
- tsutils.isImportDeclaration(node)
Always returns false therefore it continues to the next iteration in the for loop

![image](https://user-images.githubusercontent.com/11546865/94729582-2b1e0c80-0362-11eb-90ef-89ba583e3555.png)

I'm really sorry if this it not the correct place to write this down, anyway I'd appreciate any help on this.

**Comment by hsuanxyz** [comment]
I guess because the global version is too low.

here are three solutions:

1. upgrade your global tslint

`npm install tslint -g`

2. add the command to the scripts in package.json, and then use `npm run lint:fix `

```json
{
  "scripts": {
    "lint:fix": "tslint --project tsconfig.json --fix"
  }
} 
```

3. run from `node_modules/.bin/tslint`

`node_modules/.bin/tslint --project tsconfig.json --fix`

**Comment by xjuanc** [comment]
Thanks a lot, worked great
